#! /bin/bash


echo -e "Enter the file name : \c "
read file


if [ -e $file ] 
then
  echo -e "Enter the new Extension  : \c "
  read extension
    new_file="${file}${extension}"
    mv "$file" "$new_file"
    echo "Extension $extension added to $file. File renamed to '$new_file'."
  else
    echo "File $filename does not exist."
  fi