#! /bin/bash

# Read input from the user
read -p "Enter the first number: " num1
read -p "Enter the second number: " num2

swap=$num1
num1=$num2
num2=$swap

echo "After swapping num1=$num1, num2=$num2"